---
# configure
- name: Fail if user_secrets is undefined
  fail: msg="Playbook requires passed in user_secrets dictionary"
  when: user_secrets is not defined or not user_secrets or user_secrets['admin_secret'] is not defined

- name: Build Administrator user
  user:
    name: admin
    comment: "Administrator"
    create_home: yes
    groups: sudo
    append: yes

- name: Set Admin password on remote
  become: true
  user:
    name: admin
    password: "{{ user_secrets.admin_secret }}"

