#!/bin/sh
# git-hook: post-commit
# --------------------------------------

# shellcheck source=scripts/.git-hooks/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

# shellcheck disable=SC2034
LOG_PREFIX="[.husky/post-commit]"

# shellcheck source=scripts/.git-hooks/hook-utils.sh
. "$(dirname "$0")/hook-utils.sh"

# -----------------------------------------
# main
# -----------------------------------------
if [ "$GIT_LFS_ENABLED" == "true" ]; then
    # [0] handle Git LFS (handles binary files because per line changes are not desired)
    if command -v git-lfs >/dev/null 2>&1; then
        explicit_run_cmd "git lfs post-commit $*"
    else
        error "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path."
        error "Please install to continue to use this repository!\n"
        exit 2
    fi
fi
