---
# rainfall-predictor-ansible
- name: Install Rainfall Predictor app
  hosts: gce_instances_ips
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: install
    - role: configure
      user_secrets: "{{ hostvars['localhost']['pwhashes'] }}"
    
- name: Deploy Rainfall Predictor app
  hosts: gce_instances_ips
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: run
