---
- name: Install Stackdriver Agent for Google Cloud Platform
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  roles:
    - role: stackdriver
      log_agent: yes
      sys_agent: yes
